### ISSUE TITLE
php code is not workong

### ISSUE THREAD

**Issue by Ugighy** [magepal/magento2-reindex#7]

**Comment by Ugighy** [comment]
i want to install the code but seeing this now:
Magento supports PHP 7.1.3 or later. Please read https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.htmlmacparts@es63 [~/public_html]#

can someone help me out?

**Comment by srenon** [comment]
@Ugighy .... There is no known issue with our module on 2.2.6 and so far you have provided zero information to indicate that your issue is related to our extension. 

If you need our help please take a minute or two of your time to provide more information or you can always open a paid support and we will figure out your issue for you. https://www.magepal.com/magento2/support.html
